### ISSUE TITLE
Tests are failing without SSE

### ISSUE THREAD

**Issue by akasitskyi** [taqu/cpprcoder#1]
Tests fail if I comment out this block:
```
#if defined(__AVX__)
#define CPPRCODER_USE_AVX (1)
#elif defined(__SSE2__)
#define CPPRCODER_USE_SSE2 (1)
#endif
```

Visual Studio Community 2017, 32 bit

**Comment by akasitskyi** [comment]
And the bug is:
`
         for(s32 i=1; i<CHUNKS; ++i){
            prefix_[i] = prefix_[i-1] + CHUNK_SIZE;
        }
`
missing 
            **prefix_[0] = CHUNK_SIZE;**
before the loop.

**Comment by taqu** [comment]
Thanks, i fixed it :smile:.
